no_of_sensors = 1
max_bandwidth = 20
median_computation_delay =  2.5    # run for round 2.1s
no_of_episodes = 6000
len_of_episode = 30
max_load = 5
beta = 5
alpha = 0.001
learning_rate =  1e-06
discount_rate = 0.95
gamma_decay = 5.5e-06
batch_size = 128
nS = 2*beta + 2
nA = 2**beta - 1
reward_normalization = 30
epochs = 2
exploit_or_explore = []
epsilon_curve=[]
episode_access_rate = []
avg_waiting_time = []
latencies = []
deviations = []
rewards = []
action = []
load_arr = []