no_of_sensors = 1
max_bandwidth = 20
median_computation_delay = 1.2
no_of_episodes = 20
len_of_episode = 30
max_load = 5 # make it 20
beta = 10
alpha = 0.003
# learning_rate =  0.0001
reward_normalization = 1
learning_rate =  1e-07
discount_rate = 0.95
gamma_decay = 3.33e-06
batch_size = 128
epochs = 1
nS = 2*beta + 3
nA = 2**beta - 1
exploit_or_explore = []
epsilon_curve=[]
episode_access_rate = []
avg_waiting_time = []
latencies = []
deviations = []
rewards = []
action = []
load_arr = []